export interface CapabilityPageDefinition {
  key: string
  summary: string
  status: string
  metrics: [string, string][]
  controls: { label: string; value: string; options?: string[] }[]
  records: { title: string; meta: string; state: string }[]
  actions: string[]
  result: string
}

export const capabilityPages: Record<string, CapabilityPageDefinition> = {
  'scenario-center': { key:'scenario-center', summary:'按行业、场景、硬件参数和适配型号组合筛选，并进入方案或需求。', status:'已筛选', metrics:[['行业','商业零售'],['场景','户外标牌'],['匹配方案','12'],['相关产品','46']], controls:[{label:'行业',value:'商业零售',options:['商业零售','智慧办公','派对娱乐']},{label:'屏幕尺寸',value:'65英寸',options:['55英寸','65英寸','75英寸']},{label:'亮度',value:'≥2500nit',options:['≥1000nit','≥2500nit']}], records:[{title:'户外高亮数字标牌方案',meta:'标准版 V3.2 · 匹配度 96%',state:'可直接购买'},{title:'全天候门店橱窗方案',meta:'高端版 V2.0 · 匹配度 89%',state:'可咨询'}], actions:['重新匹配','提交定制需求'], result:'筛选条件已生效，已按匹配度更新方案列表。' },
  'qualification-center': { key:'qualification-center', summary:'对外展示有效资质，支持证书图片、编号、签发机构、有效期和附件查验。', status:'有效', metrics:[['有效资质','6'],['认证机构','4'],['即将到期','2'],['最近更新','09-12']], controls:[{label:'资质类别',value:'企业认证',options:['企业认证','质量体系','产品认证']}], records:[{title:'ISO 9001 质量管理体系认证',meta:'编号 ISO-CN-8891 · 有效期至 2027-09-15',state:'查看证书'},{title:'企业信用等级证书 AAA',meta:'中国企业评价协会 · 有效期至 2027-03-30',state:'下载附件'}], actions:['验证证书','下载资质包'], result:'资质信息已通过有效期校验。' },
  'smart-match': { key:'smart-match', summary:'先按必选条件过滤，再综合参数、库存、预算和运营权重排序，并解释推荐原因。', status:'已生成推荐', metrics:[['必选条件','4'],['候选方案','12'],['推荐结果','3'],['最高匹配','96%']], controls:[{label:'使用场景',value:'户外商业',options:['户外商业','智慧办公','派对娱乐']},{label:'预算',value:'5–10万元',options:['5万元以内','5–10万元','10万元以上']},{label:'接口',value:'HDMI 2.1',options:['HDMI 2.0','HDMI 2.1','Type-C']}], records:[{title:'户外高亮数字标牌方案',meta:'尺寸、亮度、接口全部满足；库存紧张；预算内',state:'96%'},{title:'商业橱窗显示方案',meta:'尺寸与接口满足；亮度低 300nit，提供替代屏',state:'82%'}], actions:['查看配置清单','转需求工单'], result:'已保存本次匹配条件和推荐理由。' },
  'enterprise-register': { key:'enterprise-register', summary:'企业提交主体、联系人和营业执照，验证后进入运营审核，信用代码重复会被拦截。', status:'待初审', metrics:[['注册步骤','4/4'],['验证方式','手机+邮箱'],['资料完整度','100%'],['审核 SLA','1工作日']], controls:[{label:'企业名称',value:'信阳智造有限公司'},{label:'统一社会信用代码',value:'91411500MA9X1101XY'},{label:'联系人',value:'王敏'},{label:'营业执照',value:'business-license.pdf'}], records:[{title:'主体信息校验',meta:'信用代码未重复，工商名称格式正确',state:'通过'},{title:'企业资质初审',meta:'提交时间 2026-09-15 10:42',state:'待审核'}], actions:['保存草稿','提交审核'], result:'注册申请 ENT-202609-019 已提交，审核结果将通过手机和邮箱通知。' },
  'password-security': { key:'password-security', summary:'支持修改与双通道找回密码、登录失败锁定、安全日志和管理员强制双因素认证。', status:'安全', metrics:[['密码强度','强'],['双因素认证','已启用'],['活跃会话','2'],['风险事件','0']], controls:[{label:'验证方式',value:'手机号',options:['手机号','邮箱']},{label:'新密码',value:'••••••••••••'}], records:[{title:'最近登录',meta:'2026-09-15 09:28 · 信阳 · Chrome',state:'正常'},{title:'密码修改',meta:'2026-08-16 14:03 · 本人操作',state:'已记录'}], actions:['发送验证码','更新密码','退出其他会话'], result:'密码已更新，其他设备会话已失效并写入安全日志。' },
  'contact-center': { key:'contact-center', summary:'维护订单、需求和通知联系人；被单据引用后可停用但不删除，并保留快照。', status:'3 位启用', metrics:[['联系人','4'],['默认收货','1'],['默认需求','1'],['已停用','1']], controls:[{label:'姓名',value:'王敏'},{label:'手机号',value:'138****6601'},{label:'业务类型',value:'订单/需求',options:['订单','需求','订单/需求']}], records:[{title:'王敏 · 默认收货联系人',meta:'采购部 · 订阅订单及物流消息',state:'启用'},{title:'李明 · 技术联系人',meta:'研发部 · 订阅需求协同消息',state:'启用'}], actions:['新增联系人','保存修改','停用联系人'], result:'联系人信息已保存，历史单据继续使用原快照。' },
  'order-evaluation': { key:'order-evaluation', summary:'订单全部签收后可评价一次，覆盖质量、交付、服务；低于 3 分自动生成跟进任务。', status:'待评价', metrics:[['产品质量','5分'],['交付及时','4分'],['服务体验','2分'],['修改机会','1次']], controls:[{label:'产品质量',value:'5',options:['1','2','3','4','5']},{label:'交付及时性',value:'4',options:['1','2','3','4','5']},{label:'服务体验',value:'2',options:['1','2','3','4','5']},{label:'评价内容',value:'产品符合预期，第二批物流响应需要改善。'}], records:[{title:'低分跟进规则',meta:'服务体验低于 3 分，通知销售与运营',state:'将触发'},{title:'可见范围',meta:'仅企业客户与平台内部可见',state:'内部'}], actions:['上传图片','提交评价'], result:'评价已提交，已生成跟进事项 FUP-202609-008。' },
  'lead-center': { key:'lead-center', summary:'主动咨询或采购意向生成线索，按企业、联系方式、对象和时间窗口去重并分派。', status:'跟进中', metrics:[['我的线索','5'],['新提交','1'],['跟进中','3'],['已完成','1']], controls:[{label:'线索类型',value:'采购意向',options:['采购意向','产品咨询','方案需求']},{label:'关联对象',value:'65英寸户外高亮屏'}], records:[{title:'LEAD-202609-086 · 批量屏采购咨询',meta:'负责人 王销售 · 关联 DEM-202609-031',state:'跟进中'},{title:'LEAD-202609-073 · 音响套料意向',meta:'同企业7天内重复，已合并',state:'已去重'}], actions:['提交新线索','查看跟进记录','转需求工单'], result:'线索已保存并完成去重校验，运营将在 4 小时内跟进。' },
  'import-export-center': { key:'import-export-center', summary:'按业务对象使用模板预校验、异步执行、错误报告、脱敏与限时下载。', status:'处理中', metrics:[['运行任务','2'],['今日完成','8'],['异常行','4'],['下载有效期','24小时']], controls:[{label:'业务对象',value:'产品',options:['产品','方案','需求计划','联系人']},{label:'模板版本',value:'产品模板 V2.3',options:['产品模板 V2.3','产品模板 V2.2']}], records:[{title:'IMP-20260915-03 · 产品批量上传',meta:'已处理 860/1000 行 · 预计剩余 20 秒',state:'86%'},{title:'EXP-20260915-08 · 订单清单导出',meta:'手机号已脱敏 · 下载至 09-16 10:30',state:'可下载'}], actions:['下载模板','新建导入','下载错误报告'], result:'异步任务已创建，可关闭页面并在完成后接收站内消息。' },
  'permission-center': { key:'permission-center', summary:'组合菜单、按钮、接口、数据和字段权限，支持跨组织限时授权、复制、转移及审计。', status:'策略生效', metrics:[['角色','9'],['策略','42'],['临时授权','2'],['今日变更','3']], controls:[{label:'角色',value:'企业采购子账号',options:['企业采购子账号','平台运营','销售人员']},{label:'数据范围',value:'本人数据',options:['本人数据','本企业','指定组织']},{label:'订单金额字段',value:'可见',options:['可见','脱敏','隐藏']}], records:[{title:'菜单与按钮',meta:'需求查看/新增；订单查看/提交；企业主体只读',state:'已配置'},{title:'跨组织授权 AUTH-018',meta:'豫南区域 · 截止 2026-09-30',state:'临时'}], actions:['复制角色权限','转移待办与数据','保存策略'], result:'权限策略已发布，变更前后值已写入审计日志。' },
  'workflow-designer': { key:'workflow-designer', summary:'可视化配置顺序、条件分支、并行会签、驳回、撤回、转办和受控业务动作。', status:'V3 已发布', metrics:[['流程节点','7'],['条件分支','2'],['运行实例','31'],['版本','V3']], controls:[{label:'流程',value:'订单审核流程',options:['订单审核流程','产品发布流程','企业注册流程']},{label:'完成后通知',value:'提交人+企业主账号',options:['提交人','提交人+企业主账号','指定角色']}], records:[{title:'提交订单',meta:'创建审批任务并通知订单审核员',state:'开始'},{title:'金额 ≥ 10万元',meta:'条件分支 → 财务会签',state:'条件'},{title:'审核通过',meta:'更新订单状态并通知客户',state:'结束'}], actions:['添加条件分支','校验流程','发布新版本'], result:'流程校验通过并发布为 V4，新实例将使用新版本。' },
  'message-center': { key:'message-center', summary:'统一管理站内信、邮件和内部通讯适配器，支持模板、已读确认、失败重试和升级告警。', status:'运行中', metrics:[['今日发送','286'],['成功率','98.6%'],['待重试','2'],['重要未读','9']], controls:[{label:'事件',value:'订单审核完成',options:['订单审核完成','需求即将超时','资质即将到期']},{label:'渠道',value:'站内信+邮件',options:['站内信','站内信+邮件','内部通讯']}], records:[{title:'MSG-20260915-221 · 订单确认邮件',meta:'SMTP 超时 · 已重试 2/3 次',state:'待重试'},{title:'MSG-20260915-218 · 需求 SLA 提醒',meta:'站内信送达，负责人未读',state:'待确认'}], actions:['预览模板','立即重试','保存规则'], result:'消息规则已保存；失败消息已进入重试队列。' },
  'i18n-preview': { key:'i18n-preview', summary:'菜单、按钮、提示及运营内容支持中英文；英文缺失时回退中文并标记待补译。', status:'English 预览', metrics:[['界面词条','486'],['已翻译','98%'],['内容条目','216'],['待补译','4']], controls:[{label:'预览语言',value:'English',options:['中文','English']},{label:'缺失策略',value:'回退中文',options:['回退中文','隐藏内容']}], records:[{title:'Outdoor High-brightness Signage Solution',meta:'方案标题及详情已完成英文发布',state:'EN 已发布'},{title:'国庆期间物流服务安排',meta:'英文正文缺失，当前展示中文',state:'回退中文'}], actions:['切换预览','导出待翻译词条','提交英文审核'], result:'语言预览已切换，缺失内容已按规则回退中文。' },
  'product-publish': { key:'product-publish', summary:'录入物料、参数、图片和分类，草稿经内容审核后发布；支持定时上架、下架失效和版本留痕。', status:'待审核', metrics:[['资料完整度','92%'],['当前版本','V2.3'],['计划上架','09-18'],['关联方案','6']], controls:[{label:'物料编码',value:'XY-LCD-650H'},{label:'多级分类',value:'商显事业部 / 液晶显示 / 高亮屏'},{label:'发布动作',value:'定时上架',options:['审核后立即上架','定时上架','保存草稿']}], records:[{title:'基础字段同步',meta:'名称、规格、单位来自 XTS Mock',state:'已同步'},{title:'门户展示字段',meta:'图片、详情、资料和搜索标签由 B2B 维护',state:'待审核'}], actions:['保存草稿','提交审核','立即下架'], result:'产品版本已提交审核；原线上版本在新版本发布前保持可见。' }
}

export const capabilityPageKeys = Object.keys(capabilityPages)

export function getCapabilityPage(key: string) {
  return capabilityPages[key]
}
